modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="morebushes"
version="3.0.0"
displayName="More Bushes"
authors="Spucio"
description='''More Bushes mod for Forge 1.20.1'''

[[dependencies.morebushes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.morebushes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"